// Previous Year Grand Finale Teams DATA
const previousYearGrandFinaleTeamsAPI = [
  {
    id: 1,
    PSID: "SM601",
    themeName: "Social Media",
    teamLeaderName: "Aman kumar Kushwaha",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Tracking intial and last IP address, and URL of false photographs , videos, documents or audio posted on the social media platforms.Global Photo video search report. Social Media link, local link, Friend Group Circle. Device Identification.",
    collage: "Jai Narain College of Technology (JNCT)",
  },
  {
    id: 2,
    PSID: "AG102",
    themeName: "Agri-Tech",
    teamLeaderName: "Sudhanshu Yadav",
    organization: " ITSC Ltd",
    PSCategory: "Software/Hardware",
    problemStatement:
      "Crop Identification using Machine Learning Model, which will help farmers for better judgement of healthy crop.",
    collage: "Sagar Institute of science technology and Research  ",
  },
  {
    id: 3,
    PSID: "CD801",
    themeName: "Criminal Database",
    teamLeaderName: "Anjali Mishra",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Maintaining police station wise data of all thieves,gangsters,vehical thieves, masked/hidden people. Maintaining the data of all criminals along with their previously registered crimes and the actions taken against the crime. ",
    collage: "Sagar Institute of science technology and Research ",
  },
  {
    id: 4,
    PSID: "VT701",
    themeName: "Vehical Theft",
    teamLeaderName: "Shad Warsi",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Identification of hot-spot vehical theft areas with the help of CCTV / City Survillance Camera. Alert message to be generated as soon the theft vehicle crosses a survillance Camera.",
    collage: "Jai Narain College of Technology(JNCT)",
  },
  {
    id: 5,
    PSID: "CD801",
    themeName: "Criminal Database",
    teamLeaderName: "Jagdeep Pandey",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Maintaining police station wise data of all thieves,gangsters,vehical thieves, masked/hidden people. Maintaining the data of all criminals along with their previously registered crimes and the actions taken against the crime.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 6,
    PSID: "CD801",
    themeName: "Criminal Database",
    teamLeaderName: "Ankit Mewada",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Maintaining police station wise data of all thieves,gangsters,vehical thieves, masked/hidden people. Maintaining the data of all criminals along with their previously registered crimes and the actions taken against the crime.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 7,
    PSID: "ET401",
    themeName: "Edu Tech.",
    teamLeaderName: "Harsh Kamde",
    organization: "DRMZ Tech",
    PSCategory: "Software",
    problemStatement:
      "WebAPP like Udemy in which I as instructor can upload courses. The user can buy any course. After they buy through a paymet gateway, they get access to the course and able to watch in an inbuilt video player.. Login  functionality needed to be implemented for both instructor and user. ",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 8,
    PSID: "FE503",
    themeName: "Force Engagement",
    teamLeaderName: "Uma Shankar Mishra",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement: " Daily duty details. Postings and transfers details. ",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 9,
    PSID: "AG102",
    themeName: "Agri-Tech",
    teamLeaderName: "Raja Ahirwar",
    organization: "ITSC LTD",
    PSCategory: "Software/Hardware",
    problemStatement:
      "Crop Identification using Machine Learning Model, which will help farmers for better judgement of healthy crop.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 10,
    PSID: "FE501",
    themeName: "Force Engagement",
    teamLeaderName: "Hariom Mewada",
    organization: "MP Police Crime Brach",
    PSCategory: "Software",
    problemStatement:
      "Availability of all posted officers and Police personnels in police stations, status of work assigned with description and Progress. ",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 11,
    PSID: "SM601",
    themeName: "Social Media",
    teamLeaderName: "Deewan Singh Mewada",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Tracking intial and last IP address, and URL of false photographs , videos, documents or audio posted on the social media platforms.Global Photo video search report. Social Media link, local link, Friend Group Circle. Device Identification.",
    collage: "Jai Narain Collage of Technology(JNCT) ",
  },
  {
    id: 12,
    PSID: "HT303",
    themeName: "Health-Tech",
    teamLeaderName: "Bharat Joshi",
    organization: "DRMZ Tech",
    PSCategory: "Software",
    problemStatement:
      "A patient management and video conference APP in which doctor and pateint can communicate on live video, the patient unique data should be stored in the database with each prescription.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 13,
    PSID: "HT303",
    themeName: "Health-Tech",
    teamLeaderName: "Yogesh Kumar Soni",
    organization: "DRMZ Tech",
    PSCategory: "Software",
    problemStatement:
      "A patient management and video conference APP in which doctor and pateint can communicate on live video, the patient unique data should be stored in the database with each prescription.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 14,
    PSID: "CD801",
    themeName: "Criminal Database",
    teamLeaderName: "Roshni Maran",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Maintaining police station wise data of all thieves,gangsters,vehical thieves, masked/hidden people. Maintaining the data of all criminals along with their previously registered crimes and the actions taken against the crime.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 15,
    PSID: "AG102",
    themeName: "Agri-Tech",
    teamLeaderName: "Kulsum Jahan",
    organization: "ITSC LTD",
    PSCategory: "Software/Hardware",
    problemStatement:
      "Crop Identification using Machine Learning Model, which will help farmers for better judgement of healthy crop.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 16,
    PSID: "HT301",
    themeName: "Health-Tech",
    teamLeaderName: "Ankush Mishra",
    organization: "ITSC LTD",
    PSCategory: "Software",
    problemStatement:
      "Automatic recognition of Human Disease using radiological data.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 17,
    PSID: "FE503",
    themeName: "Force Engagement",
    teamLeaderName: "Priyanshu Janoriya",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement: "Daily duty details. Postings and transfers details.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 18,
    PSID: "MS202",
    themeName: "Miscellaneous",
    teamLeaderName: "Siddharth Rajput",
    organization: "DRMZ Tech",
    PSCategory: "Software",
    problemStatement:
      "Generate and send PDF or JPG certificate. The App should include a template in which data can be changed. Also, the user will add the list of emails and name of person in the App. App ned to change the name in each certificate and send individual mail to each person with certificate attached.",
    collage: "Jai Narain Collage of Technology(JNCT)",
  },
  {
    id: 19,
    PSID: "HT301",
    themeName: "Health-Tech",
    teamLeaderName: "Gunja Kumari",
    organization: "ITSC LTD",
    PSCategory: "Software",
    problemStatement:
      "Automatic recognition of Human Disease using radiological data.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 20,
    PSID: "FE501",
    themeName: "Force Engagement",
    teamLeaderName: "Amit patel",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Availability of all posted officers and Police personnels in police stations, status of work assigned with description and Progress.",
    collage: "Sage University Bhopal",
  },
  {
    id: 21,
    PSID: "ET401",
    themeName: "Edu-Tech",
    teamLeaderName: "Kuldeep Kamare",
    organization: "DRMZ Tech",
    PSCategory: "Software",
    problemStatement:
      "WebAPP like Udemy in which I as instructor can upload courses. The user can buy any course. After they buy through a paymet gateway, they get access to the course and able to watch in an inbuilt video player.. Login  functionality needed to be implemented for both instructor and user.",
    collage: "Bansal Institute of Science and Technology",
  },
  {
    id: 22,
    PSID: "SM601",
    themeName: "Social Media",
    teamLeaderName: "Pawan Sondhiya",
    organization: "MP police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Tracking intial and last IP address, and URL of false photographs , videos, documents or audio posted on the social media platforms.Global Photo video search report. Social Media link, local link, Friend Group Circle. Device Identification.",
    collage: "Jai Narain Collage of Technology(JNCT)",
  },

  {
    id: 23,
    PSID: "CD801",
    themeName: "Criminal Database",
    teamLeaderName: "Archi Kirar",
    organization: "MP Police Crime Database",
    PSCategory: "Software",
    problemStatement:
      "Maintaining police station wise data of all thieves,gangsters,vehical thieves, masked/hidden people. Maintaining the data of all criminals along with their previously registered crimes and the actions taken against the crime.",
    collage: "Sage University Bhopal",
  },
  {
    id: 24,
    PSID: "SM601",
    themeName: "Social Media",
    teamLeaderName: "Mridul Chaturvedi",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Tracking intial and last IP address, and URL of false photographs , videos, documents or audio posted on the social media platforms.Global Photo video search report. Social Media link, local link, Friend Group Circle. Device Identification.",
    collage: "Jai Narain Collage of Technology(JNCT)",
  },
  {
    id: 25,
    PSID: "AG102",
    themeName: "Agri-Tech",
    teamLeaderName: "Komal Jethwani",
    organization: "ITSC LTD",
    PSCategory: "Software/Hardware",
    problemStatement:
      "Crop Identification using Machine Learning Model, which will help farmers for better judgement of healthy crop.",
    collage: "Lakshmi Narain  Collage of Technology",
  },
  {
    id: 26,
    PSID: "VT701",
    themeName: "Vehical Theft",
    teamLeaderName: "Avanish Pathak",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Identification of hot-spot vehical theft areas with the help of CCTV / City Survillance Camera. Alert message to be generated as soon the theft vehicle crosses a survillance Camera.",
    collage: "Jai Narain Collage of Technology(JNCT)",
  },
  {
    id: 27,
    PSID: "ET401",
    themeName: "Edu-Tech",
    teamLeaderName: "Ayush Dewang",
    organization: "DRMZ Tech",
    PSCategory: "Software",
    problemStatement:
      "WebAPP like Udemy in which I as instructor can upload courses. The user can buy any course. After they buy through a paymet gateway, they get access to the course and able to watch in an inbuilt video player.. Login  functionality needed to be implemented for both instructor and user.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 28,
    PSID: "AG102",
    themeName: "Agri-Tech",
    teamLeaderName: "Sohil Saudagar",
    organization: "ITSC LTD",
    PSCategory: "Software/Hardware",
    problemStatement:
      "Crop Identification using Machine Learning Model, which will help farmers for better judgement of healthy crop.",
    collage: "Technocrats Institute of Technology ",
  },
  {
    id: 29,
    PSID: "ET401",
    themeName: "Edu-Tech",
    teamLeaderName: "Rythan Asthana",
    organization: "DRMZ Tech",
    PSCategory: "Software",
    problemStatement:
      "WebAPP like Udemy in which I as instructor can upload courses. The user can buy any course. After they buy through a paymet gateway, they get access to the course and able to watch in an inbuilt video player.. Login  functionality needed to be implemented for both instructor and user.",
    collage: "Lakshmi Narain Collage of Technology",
  },
  {
    id: 30,
    PSID: "AG102",
    themeName: "Agri-Tech",
    teamLeaderName: "Kratin Mourya",
    organization: "ITSC LTD",
    PSCategory: "Software/Hardware",
    problemStatement:
      "Crop Identification using Machine Learning Model, which will help farmers for better judgement of healthy crop.",
    collage: "Lakshmi Narain Collage of Technology",
  },
  {
    id: 31,
    PSID: "HT303",
    themeName: "Health-Tech",
    teamLeaderName: "Atul Gupta",
    organization: "DRMZ Tech",
    PSCategory: "Software",
    problemStatement:
      "A patient management and video conference APP in which doctor and pateint can communicate on live video, the patient unique data should be stored in the database with each prescription.",
    collage: "Technocrats Institute of Technology ",
  },
  {
    id: 32,
    PSID: "FE503",
    themeName: "Force Engagement",
    teamLeaderName: "Mohit Yadav",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement: "Daily duty details. Postings and transfers details.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 33,
    PSID: "AG102",
    themeName: "Agri-Tech",
    teamLeaderName: "Arpit Singh",
    organization: "ITSC LTD",
    PSCategory: "Software/Hardware",
    problemStatement:
      "Crop Identification using Machine Learning Model, which will help farmers for better judgement of healthy crop.",
    collage: "Lakshmi Narain Collage of Technology",
  },
  {
    id: 34,
    PSID: "HT301",
    themeName: "Health-Tech",
    teamLeaderName: "Vanshika Jain",
    organization: "ITSC LTD",
    PSCategory: "Software",
    problemStatement:
      "Automatic recognition of Human Disease using radiological data.",
    collage: "Lakshmi Narain Collage of Technology",
  },
  {
    id: 35,
    PSID: "HT301",
    themeName: "Health-Tech",
    teamLeaderName: "Rupa Singh",
    organization: "ITSC LTD",
    PSCategory: "Software",
    problemStatement:
      "Automatic recognition of Human Disease using radiological data.",
    collage: "Technocrafts Institute of Technology ",
  },
];

// Previous Year Winners DATA
const previousYearWinnersAPI = [
  {
    id: 1,
    PSID: "HT303",
    themeName: "Health-Tech",
    teamLeaderName: "Yogesh Kumar Soni",
    organization: "DRMZ Tech",
    PSCategory: "Software",
    problemStatement:
      "A patient management and video conference APP in which doctor and pateint can communicate on live video, the patient unique data should be stored in the database with each prescription.",
    collage: "Sagar Institute of Science Technology and Research",
  },
  {
    id: 2,
    PSID: "FE501",
    themeName: "Force Engagement",
    teamLeaderName: "Amit patel",
    organization: "MP Police Crime Branch",
    PSCategory: "Software",
    problemStatement:
      "Availability of all posted officers and Police personnels in police stations, status of work assigned with description and Progress.",
    collage: "Sage University Bhopal",
  },
  {
    id: 3,
    PSID: "AG102",
    themeName: "Agri-Tech",
    teamLeaderName: "Komal Jethwani",
    organization: "ITSC LTD",
    PSCategory: "Software/Hardware",
    problemStatement:
      "Crop Identification using Machine Learning Model, which will help farmers for better judgement of healthy crop.",
    collage: "Lakshmi Narain  Collage of Technology",
  },
];

export { previousYearGrandFinaleTeamsAPI, previousYearWinnersAPI };
